profile::software_stack::lmod_default_modules:
  - StdEnv/2020
  - ipython-kernel/3.8
  - spark/3.3.0
  - scipy-stack/2020a

jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/bin/python3
jupyterhub::kernel::venv::prefix: /opt/ipython-kernel-3.8
